# Generated by Django 3.2.14 on 2022-08-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-event_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='post',
            name='event_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
