# Generated by Django 3.2.14 on 2025-11-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('uk_garage', 'UK Garage'), ('house', 'House'), ('techno', 'Techno'), ('trance', 'Trance'), ('hardstyle', 'Hardstyle'), ('electronic', 'Electronic'), ('disco', 'Disco'), ('jungle', 'Jungle')], default='electronic', max_length=50),
        ),
    ]
